#!/bin/bash

cwd=$(pwd)
copyfile="/tmp/copypaste.$USER"

touch $copyfile
rm $copyfile

if [ $# -eq 0 ]; then
    echo "Nothing to copy!"
    exit 1
fi

for var in "$@"
do
    if [[ "$var" = /* ]]; then # Absolute path
    	filename="$var"
    else                       # Relative path
    	filename="$cwd/$var"
    fi

    echo "Copying $filename"
    echo "$filename" >> $copyfile	
done
