#!/bin/bash

cwd=$(pwd)
copyfile="/tmp/copypaste.$USER"

touch $copyfile
rm $copyfile

for var in "$@"
do
    if [[ "$var" = /* ]];
    then
	echo "$var" >> $copyfile
    else
	echo "$cwd/$var" >> $copyfile
    fi
done
