#!/bin/bash

cwd=$(pwd)
copyfile="/tmp/copypaste.$USER"

touch $copyfile
rm $copyfile

if [[ $# -eq 0 ]];
then
    echo "Nothing to copy!"
    exit
fi

for var in "$@"
do
    if [[ "$var" = /* ]];
    then
	filename="$var"
    else
	filename="$cwd/$var"
    fi
    
    if [ ! -f "$filename" ];
    then
	echo "$filename: File not found!"
    else
	echo "$filename" >> $copyfile	
    fi
done
