#!/bin/bash

copyfile="/tmp/copypaste.$USER"

if [ ! -f "$copyfile" ]; then
    echo "Nothing to paste!"
    exit 1
fi

if [ "$#" -eq 1 ]; then
    outpath="$1"
elif [ "$#" -eq 0 ]; then
    outpath="."
else
    echo "More than 1 argument (usage: \"paste [outdir]\")"
    exit 1
fi

while read -r line;
do
    cp -a "$line" "$outpath"
    if [ "$?" -eq 0 ]; then
        echo "Copied $line to $outpath"
    else
        echo "Failed to copy $line to $outpath"
    fi
done < $copyfile
